# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Name of the workflow
name: Node.js CI

# Specifies when the workflow should be triggered
on:
    # Trigger on push to main
    push:
        branches:
            - main

    # Trigger on pull requests targeting main
    pull_request:
        branches:
            - main

# Defines the jobs that the workflow will execute
jobs:
    build:
        # Runner environment
        runs-on: ubuntu-latest

        # Matrix strategy to test multiple Node versions
        strategy:
            matrix:
                node-version: [16.x, 18.x]

        # Steps executed in order
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v4

            # Setup Node.js
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            # Install dependencies
            - name: Install dependencies
              run: npm ci

            # Run linter for code quality check
            - name: Run Linter
              run: npm run lint

            # Run tests
            - name: Run Test
              run: npm run test
             
            # Build the application (only if build script exists)
            - name: Build
              run: npm run build --if-present

            # Run tests
            - name: Test
              run: npm test

            - name: Install Heroku CLI # <- IMPORTANT!!! Make sure the cli is installed before using the action
              uses: actions/checkout@v2
              run: |
                curl https://cli-assets.heroku.com/install.sh | sh

            - name: Deploy to Heroku
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: akhileshns/heroku-deploy@v3.14.15 # This is the action
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: "your-unique-heroku-app-name" # must be unique in Heroku
                heroku_email: "your-email@example.com"
                

